### ISSUE TITLE
Missing egui serde support?

### ISSUE THREAD

**Issue by jorgeja** [setzer22/egui_node_graph#15]
Hey, been looking at the "persistence" feature. It seems to be missing the "egui/serde" feature? Seems to affect egui::Pos2 and egui::Vec2 uses

**Comment by setzer22** [comment]
I just pushed a new change in 4aa2d9e, can you check if that solves the issue?

**Comment by jorgeja** [comment]
Sorry, forgot about this. Yes that fixed it :)

**Comment by setzer22** [comment]
Nice! 🎉 Closing the issue then
