### ISSUE TITLE
Add "CreatedNode" NodeResponse

### ISSUE THREAD

**Issue by jorgeja** [setzer22/egui_node_graph#3]
I was just messing around with your example and it looks really cool! For my intended use case I need to keep some external data structure up to date with your graph editor. For this use case a "CreatedNode(NodeId)" NodeResponse would be beneficial. Just tried to clone the repo and add it myself, and that was really simple :)

**Comment by setzer22** [comment]
Sounds like a good idea!

> Just tried to clone the repo and add it myself, and that was really simple :)

Would you like to submit a PR? I think this would be a good contribution

**Comment by setzer22** [comment]
Implemented by @jorgeja  in #5 (thanks! :tada:)
