### ISSUE TITLE
Bump egui version to 0.19.0

### ISSUE THREAD

**Issue by MathiasPius** [setzer22/egui_node_graph#55]
0.19.0 was released a few days ago, and some packages (like `bevy_egui`) have already moved to it, causing some incompatibilities if it's used with `egui_node_graph`.

The upgrade is completely painless, and there do not appear to be any breakages.

https://github.com/setzer22/egui_node_graph/compare/main...MathiasPius:egui_node_graph:main

**Comment by setzer22** [comment]
Sounds good! Do you mind submitting your changes as a PR?

**Comment by MathiasPius** [comment]
Not at all :)

See #56
