### ISSUE TITLE
Please add minimalistic example using bevy_egui

### ISSUE THREAD

**Issue by trsh** [setzer22/egui_node_graph#64]
I tried to figure it out my self, but some-have failed.

**Comment by setzer22** [comment]
I don't have time to add a bevy example right now :sweat_smile: but if anyone wants to contribute one, it's more than welcome!

In the meantime, perhaps you can share your attempt @trsh? I may be able to help, I can't think of anything where bevy_egui would make things different than the official example.

**Comment by trsh** [comment]
```
error[E0053]: method `value_widget` has an incompatible type for trait
  --> src\node_graph.rs:87:54
   |
87 |     fn value_widget(&mut self, param_name: &str, ui: &mut Ui) -> Vec<MyResponse> {
   |                                                      ^^^^^^^
   |                                                      |
   |                                                      expected struct `egui::ui::Ui`, found struct `Ui`
   |                                                      help: change the parameter type to match the trait: `&mut egui::ui::Ui`
   |
   = note: expected fn pointer `fn(&mut MyValueType, &str, &mut egui::ui::Ui) -> std::vec::Vec<_>`
              found fn pointer `fn(&mut MyValueType, &str, &mut Ui) -> std::vec::Vec<_>`
```

I think it expects the Ui from eframe

**Comment by Tsudico** [comment]
I think you are missing a bit from line 89. It should look like:
````Rust
     fn value_widget(&mut self, param_name: &str, ui: &mut egui::ui::Ui) -> Vec<MyResponse> {
````

**Comment by trsh** [comment]
```
error[E0053]: method `value_widget` has an incompatible type for trait
  --> src\node_graph.rs:88:54
   |
88 |     fn value_widget(&mut self, param_name: &str, ui: &mut egui::ui::Ui) -> Vec<MyResponse> {
   |                                                      ^^^^^^^^^^^^^^^^^
   |                                                      |
   |                                                      expected struct `egui::ui::Ui`, found struct `Ui`
   |                                                      help: change the parameter type to match the trait: `&mut egui::ui::Ui`
   |
   = note: expected fn pointer `fn(&mut MyValueType, &str, &mut egui::ui::Ui) -> std::vec::Vec<_>`
              found fn pointer `fn(&mut MyValueType, &str, &mut Ui) -> std::vec::Vec<_>`
```

Imports

```
use egui::{self, DragValue, TextStyle};
use egui_node_graph::*;
```
I dont get it. I feed exactly the type it asks. I do not have a repo.

**Comment by Tsudico** [comment]
Bevy_egui uses it's own egui crate as seen in this example code:
````Rust
use bevy::prelude::*;
use bevy_egui::{egui, EguiContext, EguiPlugin};
````
https://github.com/mvlabat/bevy_egui

Were you able to get a minimum bevy_egui example to run?

**Comment by trsh** [comment]
Yes. It works. So maybe these egui versions are clashing?

**Comment by trsh** [comment]
Tried to use like this

```rust
use bevy_egui::{
    egui::{self, DragValue, TextStyle},
    EguiContext, EguiPlugin,
};
```

and removed egui dep from my project. Same issue.

**Comment by trsh** [comment]
egui_node_graph has "egui 0.18.1" depency, bevy_egui "egui 0.19.0". Thats what I see in cargo.lock

**Comment by Tsudico** [comment]
You can try getting a specific commit of egui_node_graph, like: https://github.com/setzer22/egui_node_graph/commit/b1deb59af13e51edda0fbc69e29fc235b52896c6 so that they are both using egui 0.19.

You would have to update your egui_node_graph dependency in cargo.toml:
````
egui_node_graph= { git = "https://github.com/setzer22/egui_node_graph.git", rev = "b1deb59" }
````

**Comment by trsh** [comment]
Yeah. Already took latest from git and now it works. Different versions of egui was the issue

**Comment by setzer22** [comment]
Glad you figured it out! :tada: Ending up with different versions of a crate on the same project is always a headache
