### ISSUE TITLE
Hide close button of node widget

### ISSUE THREAD

**Issue by huisedenanhai** [setzer22/egui_node_graph#75]
I'm working on my render graph editor. There are two special nodes called Input and Output. They should exist for all my node graphs, can not be created by the user, nor can be deleted.

I want to hide the close button for my Input/Output node. Currently I found no existing way to do this.

There can be a method `fn can_delete(&self) -> bool` for `NodeDataTrait`, so the nodes can decide whether it is deletable.

I implemented it on my [fork](https://github.com/huisedenanhai/egui_node_graph). I can make a pr if you like.

**Comment by setzer22** [comment]
This sounds like a good feature to have! Yes, please, a PR would be great :smile:

**Comment by huisedenanhai** [comment]
PR [here](https://github.com/setzer22/egui_node_graph/pull/76)

**Comment by setzer22** [comment]
Fixed in #76
